version: "2"

formatters:
  enable:
    - gofmt

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - prealloc
    - errname

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 2m